Temporary commit before switching branches
SeungwonOck/spotify-demo pull request #23
Opened 2024-09-12 14:11 UTC by JunSehyeon

-리액트 훅 사용 수정

2024-09-12 15:05 UTC, ken-do-it approved these changes

2024-09-12 18:34 UTC, gemma-Kim requested changes

2024-09-12 18:34 UTC, gemma-Kim commented on src/pages/SearchPage/SearchPage.jsx
> +      grant_type: 'client_credentials',
axios 사용하는 게 아니라  utils 내에 api 를 사용해주세요. api 내에 이미 accessToken 구현이 다 되어 있습니다. 요청날릴 때마다 토큰을 가져오는 로직을 사용하는 건 비효율적인 것 같습니다. 다른 분들이 만드신 훅 파일 참고 부탁드려요.

2024-09-13 12:48 UTC, SeungwonOck approved these changes

2024-09-13 12:50 UTC, closed without merging